---
# https://taskfile.org

version: '2'

tasks:
  dev:
    cmds:
      - task: wp:dev
      - task: go:run

  prod:
    cmds:
      - task: clean
      - task: wp:build
      - task: go:build

  build:
    cmds:
      - task: prod

  clean:
      - rm -rf public/css
      - rm -rf public/img
      - rm -rf public/js
      - rm -rf public/bootstrap
      - rm -rf public/jquery

  test:
    cmds:
      - go test -v -p 1 ./...

  go:build:
    cmds:
      - go build -v -o ./felice-n-franz{{exeExt}} .

  go:run:
    cmds:
      - go run main.go

  wp:build:
    cmds:
      - npm --prefix ./web/ run build

  wp:dev:
    cmds:
      - npm --prefix ./web/ run dev

  npm:ci:
    cmds:
      - npm --prefix ./web/ ci

  npm:i:
    cmds:
      - rm -rf web/node_modules
      - npm --prefix ./web/ install

  bump:min:
    cmds:
      - task: bump:minor

  bump:p:
    cmds:
      - task: bump:patch

  bump:minor:
    cmds:
      - bumpy bump --minor --npm-prefix web

  bump:patch:
    cmds:
      - bumpy bump --patch --npm-prefix web

  tag:
    cmds:
      - bumpy tag

  eslint:
    cmds:
      - npm --prefix ./web/ run eslint
