---
# https://taskfile.org

version: '2'

tasks:
  dev:
    cmds:
      - task: wp:dev
      - task: go:run

  build:
    cmds:
      - task: clean
      - task: wp:build
      - task: go:build

  clean:
      - rm -rf public/css
      - rm -rf public/img
      - rm -rf public/js
      - rm -rf public/bootstrap
      - rm -rf public/jquery

  test:
    cmds:
      - cmd: go test -v -p 1 ./...
        platforms: [linux/amd64, darwin/amd64]
      - cmd: go test -v -p 1 -tags dynamic ./...
        platforms: [linux/arm64, darwin/arm64]

  go:build:
    cmds:
      - cmd: go build -v -o ./felice-n-franz{{exeExt}} .
        platforms: [linux/amd64, darwin/amd64]
      - cmd: go build -v -o ./felice-n-franz{{exeExt}} -tags dynamic .
        platforms: [linux/arm64, darwin/arm64]

  go:run:
    cmds:
      - cmd: go run main.go
        platforms: [linux/amd64, darwin/amd64]
      - cmd: go run -tags dynamic main.go
        platforms: [linux/arm64, darwin/arm64]

  wp:build:
    cmds:
      - npm --prefix ./web/ run build

  wp:dev:
    cmds:
      - npm --prefix ./web/ run dev

  npm:ci:
    cmds:
      - npm --prefix ./web/ ci

  npm:i:
    cmds:
      - rm -rf web/node_modules
      - npm --prefix ./web/ install

  eslint:
    cmds:
      - npm --prefix ./web/ run eslint
