---
# https://taskfile.org

version: '2'

tasks:
  dev:
    cmds:
      - task: wpdev
      - task: gorun

  prod:
    cmds:
      - task: clean
      - task: wpbuild
      - task: gobuild

  build:
    cmds:
      - task: prod

  clean:
      - rm -rf public/css
      - rm -rf public/img
      - rm -rf public/js
      - rm -rf public/bootstrap
      - rm -rf public/jquery

  test:
    cmds:
      - go test -v -p 1 ./...

  gobuild:
    cmds:
      - go build -v -o ./felice-n-franz{{exeExt}} .

  gorun:
    cmds:
      - go run main.go

  wpbuild:
    cmds:
      - npm --prefix ./web/ run build

  wpdev:
    cmds:
      - npm --prefix ./web/ run dev

  npmci:
    cmds:
      - npm --prefix ./web/ ci

  npmi:
    cmds:
      - rm -rf web/node_modules
      - npm --prefix ./web/ install

  bump-min:
    cmds:
      - task: bump-minor

  bump-p:
    cmds:
      - task: bump-patch

  bump-minor:
    cmds:
      - bumpy-ride bump --minor --npm-prefix web

  bump-patch:
    cmds:
      - bumpy-ride bump --patch --npm-prefix web

  tag:
    cmds:
      - bumpy-ride tag

  eslint:
    cmds:
      - npm --prefix ./web/ run eslint
